### ISSUE TITLE
Makefileか何かを用意する。

### ISSUE THREAD

**Issue by nna774** [kmc-jp/bushi-template2#29]
今は https://github.com/kmc-jp/bushi-template2/blob/master/build.rb にてビルドされている。

現在の問題
- ビルド方法がわかりづらい。
  - https://github.com/kmc-jp/bushi-template2/blob/d46355190019690abca2748c7db2986abf77c635/.github/workflows/build.yaml#L10 このコマンドを叩くのが正解です。
- https://github.com/kmc-jp/bushi-template2/issues/10
  - ビルドが遅い(各々の記事が更新されていなくても、毎回pandocが走る)。
  - せめてpandocを並列に実行するなどは今のままでもできるが……？
- https://github.com/kmc-jp/bushi-template2/issues/8

**Comment by hanazuki** [comment]
dev-containerってやつとかでうまくプレビューできるようにしたい
