### ISSUE TITLE
このレポジトリをpublicにする。

### ISSUE THREAD

**Issue by nna774** [kmc-jp/bushi-template2#4]
したい。

作成者からの許諾は得ているので、後は他に混じっている外のコードのライセンスだけ整えればよい。

- luakmcbook.dtx
  - https://github.com/kmc-jp/bushi-template2/blob/daa5182bf3ad929e78874b9cfb2eb32fd95df007/luakmcbook.dtx#L8 `Pandoc のテンプレからもってきたやつ` 
  - https://github.com/jgm/pandoc-templates/blob/master/default.latex たぶんこれ。
  - [README](https://github.com/jgm/pandoc-templates#:~:text=All%20of%20the%20templates%20in%20this%20repository%20are%20dual%20licensed%2C%20under%20both%20the%20GPL%20(v2%20or%20higher%2C%20same%20as%20pandoc)%20and%20the%20BSD%203-clause%20license%20(included%20below).)によると、
  - `All of the templates in this repository are dual licensed, under both the GPL (v2 or higher, same as pandoc) and the BSD 3-clause license (included below).`
  - なのでまぁなんとかなりはしそう。
- 他にはないか？

**Comment by nna774** [comment]
した。

**Comment by hanazuki** [comment]
BSDライセンスだとすると，リポジトリに著作権表記とライセンス文を含める必要がありそう

- BSD-3 https://github.com/jgm/pandoc-templates (幅だけ指定したときに画像が縦長にならないようにする)
- BSD-2 https://github.com/zr-tex8r/BXjscls/blob/master/bxjscls.dtx (chapter/sectionの再定義)
- 出処不明 https://github.com/kmc-jp/bushi-template2/blob/245cda48a9d5f2dc6b68fc40508da26cd58e71dc/luakmcbook.dtx#L34-L64
